[build]
publish = "build/html"
command = "make"

# Permanent redirect from the netlify domain to the canonical domain
[[redirects]]
from = "https://org-pietroalbini-www.netlify.com/*"
to = "https://www.pietroalbini.org/:splat"
status = 301
force = true

# Permanent redirect from pietroalbini.com to pietroalbini.org
[[redirects]]
from = "https://pietroalbini.com/*"
to = "https://www.pietroalbini.org/:splat"
status = 301
force = true

# Permanent redirect from www.pietroalbini.com to pietroalbini.org
[[redirects]]
from = "https://www.pietroalbini.com/*"
to = "https://www.pietroalbini.org/:splat"
status = 301
force = true

# Security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Xss-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Content-Security-Policy = "default-src 'none'; script-src 'self'; style-src 'self' assets.pietroalbini.org; font-src assets.pietroalbini.org; img-src 'self' assets.pietroalbini.org"
